# Generated by Django 5.2.6 on 2025-09-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/imgs/')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='news.eventsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EventsVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/videos/')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ideos', to='news.eventsmodel')),
            ],
        ),
    ]
